export const usernameError = 'Username must be between 6 and 30 characters long.';
export const emailError = 'Please enter a valid email address.';
export const passwordError = 'Password must be atleast 8 characters long and include one letter, one number and one special symbol.';
export const firstNameError = 'First name must be between 2 and 30 characters long.';
export const lastNameError = 'Last name must be between 2 and 30 characters long.';
export const usernameRequired = 'Username is required.';
export const passwordRequired = 'Password is required.';
export const photoStoryError = 'The story behind your photo must be between 50 and 250 characters long.';
export const photoTitleError = 'Photo title must be between 4 and 30 characters long.';
export const photoRequired = 'Valid .jpg/.png file is required.';
export const contestTitleError = 'Contest title must be between 4 and 30 characters long.';
export const contestCategoryError = 'The category of your contest must be between 6 and 100 characters long.';
export const ratingRequired = 'Please select a rating for the photo from 1 to 10.'
export const commentError = 'Your comment must be between 50 and 250 characters long.';